#!/system/bin/sh

echo -n " Do you realy want to uninstall Metaon "                
read character "YES"
case $character in

clear
   echo ""
   echo "Metaon Engine uninstaller,please wait..."
sleep 3
   echo ""
   echo "Mounting /system partition..."
sleep 1
busybox mount -o remount,rw /system
   echo ""
   echo "Removing scripts,please wait..."
sleep 5


busybox rm -rf /system/etc/Backup
busybox rm -rf /system/metaon
busybox rm -rf /system/etc/entropy
busybox rm -rf /system/etc/Entropy_script
busybox rm -rf /system/etc/rngd
busybox rm -f /system/etc/hosts
busybox rm -rf /system/etc/sysctl.conf
busybox rm -f /system/etc/init.d/init.d
busybox rm -f /system/etc/init.d/92cleaner
busybox rm -f /system/etc/init.d/93kill_media_server
busybox rm -f /system/etc/init.d/94Governor_tweaks
busybox rm -f /system/etc/init.d/09sdcardspeedfix
busybox rm -f /system/etc/init.d/98metaon_engine
busybox rm -f /system/etc/init.d/darky_zipalign
busybox rm -f /system/etc/init.d/sqlite_optimize
busybox rm -f /system/etc/init.d/zipaligndata
busybox rm -f /system/etc/init.d/zipalign
busybox rm -f /system/etc/init.d/ram_manager
busybox rm -f /system/etc/init.d/91touchscreen
busybox rm -f /system/etc/init.d/EXT4_tweak
busybox rm -f /system/etc/init.d/remounti9300
busybox rm -f /system/etc/init.d/Entropy_engine
busybox rm -f /system/etc/init.d/entropy
busybox rm -f /system/etc/init.d/09RW_turbo
busybox rm -f /system/etc/init.d/fstrim
   echo ""
   echo "Removing binaries and libraries,please wait..."
sleep 5
busybox rm -f /system/bin/Metaon
busybox rm -f /system/bin/entropy_off
busybox rm -f /system/bin/entropy_on
busybox rm -f /system/bin/Entropy_engine
busybox rm -f /system/bin/tune2fs
busybox rm -f /system/xbin/openvpn
busybox rm -f /system/xbin/zipalign
busybox rm -f /system/xbin/sqlite3
busybox rm -f /system/xbin/rngd
busybox rm -f /system/xbin/entro
busybox rm -f /system/lib/libncurses.so
busybox rm -f /system/Intel
busybox rm -f /system/metaon

   echo ""
   echo "Removing metaon ENGINE A.I CORE,please wait..."
   

   echo ""
   echo "metaon ENGINE has been completely removed from your phone..."
sleep 3
   echo ""
   echo "Deleting uninstaller script from /bin directory"
sleep 2
   echo ""
   echo "Please reboot your device to remove metaon ENGINE effect now!"
busybox rm -f /system/bin/uninstaller